<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen" Version="9.0.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CamaraWin.Core\CamaraWin.Core.csproj" />
  </ItemGroup>

</Project>
