<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Centinela.Core\Centinela.Core.csproj" />
    <ProjectReference Include="..\Centinela.Media\Centinela.Media.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Centinela</AssemblyName>
    <ApplicationIcon>Assets\centinela.ico</ApplicationIcon>
    <CopyFFmpeg>true</CopyFFmpeg>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\centinela.ico" />
    <Resource Include="Assets\centinela.png" />
  </ItemGroup>

</Project>
